### ISSUE TITLE
yarn api:ref 登录apifox账号成功后选择不了项目（任何操作都是报未选择任何项目）

### ISSUE THREAD

**Issue by Lgowen** [halo951/api-refs#1]
# 版本 & 环境信息
Node: v18.17.1
"api-refs": "^1.1.5"

# 问题描述
执行  api:ref 指令登录成功apifox后，选择任何项目都显示（🚧 **未选择任何项目, 程序退出**）

# 示例代码 or 复现步骤
yarn api:ref 到【选择项目】这步操作

# 修复建议

> 如果您对这个 issue 有修复建议, 可以在这里描述或这给我提一个 pr

**Comment by Lgowen** [comment]
sorry, 才发现是使用“空格键“来选中相应的项目（这功能属实有点隐藏了）

**Comment by halo951** [comment]
哈哈 没事~
